name: Validate pull request
on:
  pull_request:
    paths-ignore:
      - "*.md"
      - "PROJECT"
      - ".gitignore"
      - ".vscode"
  workflow_dispatch:

jobs:
  test:
    name: Execute local integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: Cache Homebrew installation
        uses: actions/cache@v3
        with:
          path: |
            /home/linuxbrew/.linuxbrew
          key: ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Brewfile.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-
      - name: Install Homebrew and install packages
        shell: bash
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> ${GITHUB_PATH}
          export PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"
          brew bundle
      - name: Run tests
        shell: bash
        run: make test
  e2e-test:
      name: Run end to end tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup Go
          uses: actions/setup-go@v3
          with:
            go-version-file: go.mod
            cache: true
        - name: Cache Homebrew installation
          uses: actions/cache@v3
          with:
            path: |
              /home/linuxbrew/.linuxbrew
            key: ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Brewfile.lock.json') }}
            restore-keys: |
              ${{ runner.os }}-${{ runner.arch }}-
        - name: Install Homebrew and install packages
          shell: bash
          run: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            echo "/home/linuxbrew/.linuxbrew/bin" >> ${GITHUB_PATH}
            export PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"
            brew bundle
        - name: Run end to end tests
          shell: bash
          run: make test-e2e